//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulProje
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class okulOdevEntities : DbContext
    {
        public okulOdevEntities()
            : base("name=okulOdevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<odev_ders> odev_ders { get; set; }
        public virtual DbSet<odev_ogrenci> odev_ogrenci { get; set; }
        public virtual DbSet<odev_ogrenciders> odev_ogrenciders { get; set; }
        public virtual DbSet<odev_okulyonetim> odev_okulyonetim { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
