//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class odev_ders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public odev_ders()
        {
            this.odev_ogrenciders = new HashSet<odev_ogrenciders>();
        }
    
        public short ders_id { get; set; }
        public string ders_ad { get; set; }
        public string ders_kredi { get; set; }
        public Nullable<short> ders_okulyonetimid { get; set; }
    
        public virtual odev_okulyonetim odev_okulyonetim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<odev_ogrenciders> odev_ogrenciders { get; set; }
    }
}
